// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UAZs81i39ssTVwCblwieWVisbh5tCec',
    appId: '1:172690454475:web:2a13d36fa9305c201fa84e',
    messagingSenderId: '172690454475',
    projectId: 'cutalkv2',
    authDomain: 'cutalkv2.firebaseapp.com',
    storageBucket: 'cutalkv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6rh6qFKQhkwseddh-1vcITnv9o6KVE8I',
    appId: '1:172690454475:android:ea22a0ae0435b5ea1fa84e',
    messagingSenderId: '172690454475',
    projectId: 'cutalkv2',
    storageBucket: 'cutalkv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD462sHava4Xj0Q7JqM3YF4JiBikTjU0GM',
    appId: '1:172690454475:ios:a8bf2963bdc48ad81fa84e',
    messagingSenderId: '172690454475',
    projectId: 'cutalkv2',
    storageBucket: 'cutalkv2.appspot.com',
    iosClientId: '172690454475-2u821f4rk34meohcqvo52n0fdulq9fog.apps.googleusercontent.com',
    iosBundleId: 'com.cutalkv2.korayliman',
  );
}
